/** Small, realistic `/api/trading` responses for the dashboard's tests. */
import type {
  TradingDecisionPage,
  TradingHealthView,
  TradingOverview,
  TradingPerformanceView,
  TradingPositionsView,
  TradingReportsView,
  TradingSource,
  TradingStrategiesView,
} from "@/types/trading";

const T0 = Date.UTC(2026, 9, 10, 8, 5);

export const okSource: TradingSource = {
  state: "ok",
  detail: "",
  file_name: "paper_journal.sqlite",
  read_at_ms: T0 + 60_000,
  journal_mtime_ms: T0,
  size_bytes: 45_056,
  read_ms: 1.1,
  truncated: false,
  bad_rows: 0,
  warnings: [],
};

export const missingSource: TradingSource = {
  ...okSource,
  state: "missing",
  detail: "no journal at this path",
  journal_mtime_ms: null,
  size_bytes: null,
  read_ms: null,
};

export const overview: TradingOverview = {
  source: okSource,
  test: {
    spec_name: "forward-paper-test-1",
    spec_digest: "5fd96b583982b8c2",
    spec_matches: true,
    state: "running",
    from_ms: T0 - 10 * 3_600_000,
    until_ms: T0 - 10 * 3_600_000 + 14 * 86_400_000,
    day: 1,
    days_total: 14,
    progress: 0.03,
    runs_done: 4,
    runs_expected: 4,
    runs_missed: 0,
    last_run_ms: T0,
    next_run_ms: T0 + 4 * 3_600_000,
    code_digest: "167ea0e07e92fc25",
    refusals: 0,
  },
  accounts: [
    {
      candidate: "A",
      streams: ["A:BTC-USD", "A:ETH-USD"],
      capital: 10_000,
      cash: 10_012.5,
      equity: 10_040.25,
      return_pct: 0.004025,
      realized: 12.5,
      unrealized: 27.75,
      fees: 4.1,
      funding: 0.2,
      day_pnl: 15,
      peak_equity: 10_050,
      drawdown_now: 0.00097,
      max_drawdown: 0.004,
      kill_switch: false,
      kill_reason: "",
      halted_day: null,
      trades: 1,
      open_positions: 1,
      evaluable: false,
      min_trades: 40,
    },
    {
      candidate: "B",
      streams: ["B:BTC-USD"],
      capital: 10_000,
      cash: 10_000,
      equity: 10_000,
      return_pct: 0,
      realized: 0,
      unrealized: 0,
      fees: 0,
      funding: 0,
      day_pnl: 0,
      peak_equity: 10_000,
      drawdown_now: 0,
      max_drawdown: 0,
      kill_switch: false,
      kill_reason: "",
      halted_day: null,
      trades: 0,
      open_positions: 0,
      evaluable: false,
      min_trades: 40,
    },
  ],
  combined: {
    capital: 20_000,
    equity: 20_040.25,
    return_pct: 0.0020125,
    realized: 12.5,
    unrealized: 27.75,
    open_risk: 48.2,
    same_symbol_overlap: [],
  },
};

const noSignal = {
  id: 41,
  ts_ms: T0,
  kind: "no_signal",
  group: "no_trade" as const,
  symbol: "BTC-USD",
  stream: "B:BTC-USD",
  candidate: "B",
  reason_code: "no_crossover",
  reason: "no SMA crossover: SMA20 82727 below SMA100 84130.8 since before this bar",
  signal_code: null,
  signal_reason: null,
  side: null,
  qty: null,
  price: null,
  stop: null,
  take_profit: null,
  risk: null,
  net: null,
  r_multiple: null,
};

export const strategies: TradingStrategiesView = {
  source: okSource,
  streams: [
    {
      id: "A:BTC-USD",
      candidate: "A",
      symbol: "BTC-USD",
      interval: "1d",
      strategy: "donchian_breakout",
      params: { entry_n: 20, exit_n: 20, stop_atr: 2, tp_atr: 6, allow_short: true },
      status: "position_open",
      data_status: "ok",
      last_close_ms: T0 - 86_400_000,
      next_close_ms: T0 + 86_400_000,
      last_event: { ...noSignal, id: 40, kind: "hold", stream: "A:BTC-USD", candidate: "A", reason_code: "holding", reason: "holding long: close 82578.5 inside the 20-bar exit channel" },
      position_side: "long",
      trades: 1,
      net: 12.5,
    },
    {
      id: "B:BTC-USD",
      candidate: "B",
      symbol: "BTC-USD",
      interval: "4h",
      strategy: "sma_cross",
      params: { fast: 20, slow: 100 },
      status: "no_signal",
      data_status: "ok",
      last_close_ms: T0 - 4 * 3_600_000,
      next_close_ms: T0 + 4 * 3_600_000,
      last_event: noSignal,
      position_side: null,
      trades: 0,
      net: 0,
    },
  ],
};

export const positions: TradingPositionsView = {
  source: okSource,
  positions: [
    {
      candidate: "A",
      stream: "A:BTC-USD",
      symbol: "BTC-USD",
      side: "long",
      qty: 0.012,
      entry: 80_265.1,
      mark: 82_578.5,
      stop: 78_560,
      take_profit: 90_400,
      unrealized: 27.75,
      risk_at_stop: 48.2,
      notional: 990.94,
      funding: 0.2,
      opened_ms: T0 - 2 * 86_400_000,
      leverage: 1,
    },
  ],
  pending: [],
  risk: [
    {
      candidate: "A",
      equity: 10_040.25,
      limits: [
        { key: "open_risk", used: 0.0048, limit: 0.015, ratio: 0.32 },
        { key: "gross_exposure", used: 0.0987, limit: 1, ratio: 0.0987 },
        { key: "positions", used: 1, limit: 3, ratio: 0.333 },
        { key: "daily_loss", used: 0, limit: 0.02, ratio: 0 },
        { key: "drawdown", used: 0.00097, limit: 0.1, ratio: 0.0097 },
      ],
      kill_switch: false,
      kill_reason: "",
      halted_day: null,
    },
  ],
  same_symbol_overlap: [],
  open_risk: 48.2,
  notional: 990.94,
};

export const decisions: TradingDecisionPage = {
  source: okSource,
  items: [
    noSignal,
    {
      ...noSignal,
      id: 30,
      kind: "rejected",
      group: "signal",
      stream: "A:ETH-USD",
      candidate: "A",
      symbol: "ETH-USD",
      reason_code: "open_risk_limit",
      reason: "total open risk would exceed the limit",
      signal_code: "breakout_up",
      signal_reason: "close broke the 20-bar high",
      side: "long",
    },
  ],
  total: 2,
  next_before_id: null,
  reason_counts: [
    { kind: "no_signal", reason_code: "no_crossover", count: 1 },
    { kind: "rejected", reason_code: "open_risk_limit", count: 1 },
  ],
  streams: ["A:BTC-USD", "A:ETH-USD", "B:BTC-USD"],
};

export const performance: TradingPerformanceView = {
  source: okSource,
  by_stream: [
    {
      key: "A:BTC-USD",
      candidate: "A",
      symbol: "BTC-USD",
      strategy: "donchian_breakout",
      trades: 1,
      wins: 1,
      losses: 0,
      win_rate: 1,
      profit_factor: 99,
      avg_r: 0.26,
      net: 12.5,
      fees: 4.1,
      funding: 0.2,
      best: 12.5,
      worst: 12.5,
      avg_hold_h: 96,
    },
  ],
  by_candidate: [],
  by_symbol: [],
  equity: [
    {
      candidate: "A",
      points: [
        { ts_ms: T0 - 2 * 86_400_000, equity: 10_000 },
        { ts_ms: T0 - 86_400_000, equity: 10_012.5 },
        { ts_ms: T0, equity: 10_040.25 },
      ],
    },
    { candidate: "B", points: [{ ts_ms: T0 - 2 * 86_400_000, equity: 10_000 }] },
  ],
  criteria: { profit_factor_min: 1.2, avg_r_min: 0, max_drawdown_max: 0.1, min_trades: 40 },
  trades: [],
};

export const health: TradingHealthView = {
  source: okSource,
  streams: [
    {
      id: "A:SOL-USD",
      symbol: "SOL-USD",
      interval: "1d",
      data_status: "data stale",
      data_code: "data_problem",
      last_close_ms: T0 - 2 * 86_400_000,
      expected_close_ms: T0 - 86_400_000,
      lag_bars: 1,
      stale: true,
    },
  ],
  runs: [{ ts_ms: T0, processed: 1, skipped: {}, requests: 3, notes: [] }],
  requests_today: 27,
  request_budget_day: 300,
  request_budget_run: 40,
  incidents: [],
  last_run_ms: T0,
  next_run_ms: T0 + 4 * 3_600_000,
  run_overdue: false,
};

export const reports: TradingReportsView = { source: okSource, reports: [] };

export const RESPONSES: Record<string, unknown> = {
  overview,
  strategies,
  positions,
  decisions,
  performance,
  health,
  reports,
};
